print("Getting ready to know!")
print()
myName = input("What's your name?")
print("Hello", myName)
myFood = input("What's your favourite food?")
print("I like", myFood, "too!")
myMusic = input("What's your favourite music?")
print("I like", myMusic, "too!")
myPlace = input("Where do you live?")
print("I live in", myPlace, "too!")
print()
print("You are",myName)
print("You're probably hungry for",myFood)
print("and you're definitely getting your groove on to",myMusic)
print("living in the amazing",myPlace)

